### ISSUE TITLE
OE kelp/seagrass? + Fluidlogged API quirk / DynamicSurroundings "splash" incompatibility

### ISSUE THREAD

**Issue by Sethgno** [SirSquidly/Oceanic-Expanse#10]
when oe:kelp grows (naturally/bonemeal) the topmost kelp block will create a repeating "dynamicSurroundings splash" effect while fluidLogging is installed and DS splash is enabled. this effect will persist until the kelp is broken. ([DS splash effect occurs whenever there is "flowing water"](https://dynamicsurroundings.readthedocs.io/en/master/features/watersplash.html))

tested with other modded "underwater growth" blocks. oe kelp is only one that triggers it, and also the tall seagrass i believe.
(EDIT_2:  just realized that the other mod i tested this with was also by the author of FL API. so assumedly theres a chance that most other mods would also have this issue due to not being "in line" with FL's code, in which case it would be a "FL API + DS incompat issue" on FL/DS's side, or a "X Mod + FL issue" on every other mod's side. until then OE is the only instance i've find )

assuming that whatever causes it triggers regardless of DS being installed, it just also makes it more noticeable lol

[https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings)
**EDIT**: ~~tested with VERY old version of DS! will return with more info~~
tested with newest version of DS (3.6.1.0)

![2023-04-23_23 46 16](https://user-images.githubusercontent.com/131620592/233902435-354bc951-068d-4f0e-8f6a-1ddb84435574.png)
![2023-04-23_23 46 19](https://user-images.githubusercontent.com/131620592/233902462-bcc3be1f-9a9b-41c4-bfa6-9689f3c275c9.png)

**Comment by vico93** [comment]
I had the same issue here. Seems like the kelp leaves behind air that the other water source blocks try to fill, creating the sounds.

**Comment by SirSquidly** [comment]
This is an odd one, I've been looking into it to see why exactly it is. It might be a weird interaction between Fluidlogged and Dynamic Surroundings, as Dynamic Surroundings is checking for `Material.Water`, and Fluidlogged intentionally doesnn't use `Material.Water`.

**Comment by SirSquidly** [comment]
To be more specific, I think this issue is popping up as my mod, Oceanic Expanse, has separate blocks for Short and Tall Seagrass, along with separate blocks for Top and Mid Kelp. The Seagrass thing is fixable, although the kelp was broken up to try and lower the amount of random block updates that would be called.

I might change that behavior in the future, combining the technical blocks, although that would have to be a straight up 2.0.0 version as it wouldn't work seamlessly in a pre-made world.

**Comment by SirSquidly** [comment]
Fixed in the 1.1.0 update.

**Comment by SirSquidly** [comment]
Testing this myself, I've found the issue persists. How annoying.

**Comment by SirSquidly** [comment]
Tested, and CONFIRMED to finally be fixed 1.1.1.

If this re-appears for new plants, please make a new issue.
