### ISSUE TITLE
Conduit ability fails when standing in sea grass or kelp

### ISSUE THREAD

**Issue by darchitectlp** [SirSquidly/Oceanic-Expanse#100]
**Description**
Build a conduit in the ocean, swim in so that your head space is where the kelp or sea grass is, and notice that the night vision/fog removal fails. Swim out, immediately starts working again.

Just awesome that you've backported so many amazing things; especially the conduit. I hope you consider porting over proper biomes the way Subaquatic did... and the water bubble columns. Those are the only reasons I have both installed right now. Thanks!

**Comment by SirSquidly** [comment]
Experimentation showed this was an issue when use with Fluidlogged API, in the future, please follow the bug report guideline as to make it easier to diagnose and solve.

**Comment by SirSquidly** [comment]
Fixed in 1.1.5
