### ISSUE TITLE
oe:conduit + fluidLogged API incompatibility 

### ISSUE THREAD

**Issue by Sethgno** [SirSquidly/Oceanic-Expanse#11]
fluidlogged API disallows the conduit to activate. water doesnt flow into the conduit block space.
adding oe:conduit to the FL-API whitelist yields similar results

**Comment by SirSquidly** [comment]
Big yikes, I'm surprised I missed that!

Fixed in development workspace.

**Comment by SirSquidly** [comment]
Fixed in version 1.0.5
