### ISSUE TITLE
fluidlogged api prevents tall seagrass from being grown

### ISSUE THREAD

**Issue by Sethgno** [SirSquidly/Oceanic-Expanse#12]
when FL API is installed, right clicking seagrass with bonemeal will not "accept" the bonemeal and the tall seagrass will not spawn

right clicking bonemeal on sea floor to grow seagrass still works as intended.

**Comment by SirSquidly** [comment]
In testing, I found this also applies to Dulse.

Fixed both growth issues in development workspace.

**Comment by SirSquidly** [comment]
Fixed in version 1.0.5
