### ISSUE TITLE
loading an OE world with a fresh install of Fluidlogged API creates "air" pockets

### ISSUE THREAD

**Issue by Sethgno** [SirSquidly/Oceanic-Expanse#13]
loading with FL API into a previously generated OE world that didnt previously have FL API installed will create air pockets around topmost block of kelp and seagrass

shown: oe kelp and seagrass with BiomesOPlenty coral unaffected (just to show that its not necessarily a FL issue)
![2023-04-24_06 54 55](https://user-images.githubusercontent.com/131620592/233989112-d1a835ff-a92b-4a0f-bb34-22739c9f2c07.png)

**Comment by SirSquidly** [comment]
This actually comes down to how Fluidlogged API handles the liquid states, which can only be set when a block is being placed. As such, this isn't an issue, but is just how Fluidlogged works.

I'll add a warning to the Mod Description about this, as there aren't any easy solutions to this kind of thing, other than avoiding it,

Also Biomes O' Plenty Coral/other Aquatic Blocks don't have Fluidlogged integration.

**Comment by SirSquidly** [comment]
I added this to the [wiki page](https://github.com/SirSquidly/Oceanic-Expanse/wiki/Mod-Compatibilities) for mod compatibilities, for future reference.
