### ISSUE TITLE
Underwater torches don't work underwater

### ISSUE THREAD

**Issue by Thaumatarge** [SirSquidly/Oceanic-Expanse#15]
I tested it with latest Fluidlogged API (2.1.2) and latest Aqua Acrobatics (1.15.3). Whenever I try to place an Underwater Torch under water it just pops off like a regular torch.

**Comment by Sethgno** [comment]
that one works if you add the torch to the fluidlogged cfg whitelist

**Comment by Thaumatarge** [comment]
Should still be something that happens by default when most of the water plants happen to do it by default, but good to know.

**Comment by SirSquidly** [comment]
Yikes, that's an oversight

Fixed in development workspace.

**Comment by SirSquidly** [comment]
Fixed in version 1.0.5
