### ISSUE TITLE
Critical client crash

### ISSUE THREAD

**Issue by nocturni** [SirSquidly/Oceanic-Expanse#2]
While the server doesn't crash, the client cannot join anymore due to a crash related to an entity.

https://mclo.gs/vXBIDTl

**Comment by SirSquidly** [comment]
How odd, this has to be an issue related to the combination of mods, as it seems related to ItemStack, which ConduitEye _never_ calls or uses in any way.

If I had to predict, maybe a mod is interacting with ConduitEye as it extends EntityAnimal (for some reason????)

**Comment by nocturni** [comment]
I have no idea, I wasn't doing anything in particular at this time, I tried to remove every mod that altered vanilla minecraft and the crash still happened.

**Comment by nocturni** [comment]
Some other crash mentioned that it was related to "null" in InjectAI at line 57, I can't seem to find the crash in my files however.

**Comment by SirSquidly** [comment]
> I have no idea, I wasn't doing anything in particular at this time, I tried to remove every mod that altered vanilla minecraft and the crash still happened.

I'm 99% certain this is from UniveralTweaks in the UTMobDespawnMixin. I'm simplifying the ConduitEye entity to see if that helps or works.

> Some other crash mentioned that it was related to "null" in InjectAI at line 57, I can't seem to find the crash in my files however.

This listed issue is unrelated to InjectAI. InjectAI also shouldn't ever return null? I'll throw in a bonus check to be certain.

**Comment by SirSquidly** [comment]
Version 1.0.2 is being uploaded to Curseforge, please respond back if the issue persists in this new version.

EDIT: 1.0.2 is uploaded with the fixes.

**Comment by nocturni** [comment]
Thanks a bunch for looking into it! I'll tell you if anything goes wrong after the update (I disabled entities temporarily to prevent the crash, I'll re-enable them).
