### ISSUE TITLE
Random Clear Water Chunks

### ISSUE THREAD

**Issue by Kazupathry** [SirSquidly/Oceanic-Expanse#20]
I think Oceanic Expanse may be causing this issue, was testing it a bit, I have two pictures and a latest log.
The pictures where taken in the full modpack I was working with but I tested it with an extremely smaller version.
If needed I can get new pictures, first time posting on github.
![2023-05-12_17 20 36](https://github.com/SirSquidly/Oceanic-Expanse/assets/133454883/0f5072e6-a359-4c30-816f-956ced6f1355)
![2023-05-12_17 48 48](https://github.com/SirSquidly/Oceanic-Expanse/assets/133454883/ee7874d4-fc20-4ae1-82b4-a3adebc84262)
[latest.log](https://github.com/SirSquidly/Oceanic-Expanse/files/11468325/latest.log)

**Comment by SirSquidly** [comment]
I made no tweaks to Water Rendering, so I don't see how Oceanic Expanse can be responsible whatsoever to this.

Also, the .log makes no mention of issues related to Oceanic Expanse (that are not already known)

**Comment by Kazupathry** [comment]
I tried with and without Oceanic Expanse, unless it's an incompatibility issue than I'm not sure, cause I never saw the clear chunks without the mod installed, if there is any other information I can get for you I'll try to get it

**Comment by Kazupathry** [comment]
So I experienced the same issue with a mod called Greenery today, I think it's some kind of incompatibility with mods that add kelp, since after removing Greenery the oceans didn't have clear chunks everywhere, I'm not sure what causes this issue but it's not an issue I think you can fix either way so I am sorry about this, if there is anything you might know about the issue it would be nice to here about it though.

**Comment by SirSquidly** [comment]
> So I experienced the same issue with a mod called Greenery today, I think it's some kind of incompatibility with mods that add kelp, since after removing Greenery the oceans didn't have clear chunks everywhere, I'm not sure what causes this issue but it's not an issue I think you can fix either way so I am sorry about this, if there is anything you might know about the issue it would be nice to here about it though.

That would be odd, considering we use _completely_ different methods if implementing water plants like Kelp.

**Comment by SirSquidly** [comment]
I'm closing this for now, as there isn't enough information on how this issue is being caused, and I have never reproduced it at any point during my testing.

**Comment by MrRedstoneA1** [comment]
I also had this issue. Might be related to optifine? I'll have to test.

**Comment by Potatoo-Cake** [comment]
had the same issue, but disabling both seagrass patch and kelp forest in worldgen fixes it

**Comment by Kazupathry** [comment]
The issue is an incompatibility with Optifines "Render Regions" setting

**Comment by MrRedstoneA1** [comment]
> The issue is an incompatibility with Optifines "Render Regions" setting

I had it disabled though.
