### ISSUE TITLE
Question about the original features of OE and future MC versions

### ISSUE THREAD

**Issue by vico93** [SirSquidly/Oceanic-Expanse#21]
Basically, is there any chance for us to see the original (non-backport) features added by OE ported for future Minecraft versions?

If not, can others do it? - i'm tempted to ask on Fabric Discord to see if some modder have interest because the OE original features are amazing!

**Comment by SirSquidly** [comment]
Ports to future versions are a possibility. If I clearly abandon this project, go ahead and port it without me, as long as you leave proper credits.

Also please use the Discussions section in the future, as to keep the issues tracker clean.

**Comment by vico93** [comment]
> Also please use the Discussions section in the future, as to keep the issues tracker clean.

Sorry, i'm not habitued to Github discussions yet (since some repos still have it enabled).
