### ISSUE TITLE
[Suggestion] Change default Glow Squid spawn height + make it configurable?

### ISSUE THREAD

**Issue by xJon** [SirSquidly/Oceanic-Expanse#26]
The current height conditions are very rare for default 1.12.2 generation, even for the Deep Ocean biome.
Testing two Deep Ocean biomes, the deepest ocean floor found was at `Y=31`.

~~By the way, don't tell Mojang but have you considered making the Glow Squid actually glow?~~

**Comment by SirSquidly** [comment]
I'll tweak the spawn height, as yeah that's an oversight.

Also, I'll be real, making Glow Squids actually glow would be difficult to program, and would add literally nothing. I'd recommend looking into other mods for dynamic lighting.

**Comment by Sethgno** [comment]
> add literally nothing

_regular-squid bias in play_

**Comment by SirSquidly** [comment]
Added a Config option for Glow Squid spawn height in the config, and set the default to be 40.

> _regular-squid bias in play_

I actually love the Glow Squid, that's why I improved the looks of it a ton in my mod.

Also, _that's why it's the only mob in the mod you cannot disable._

**Comment by SirSquidly** [comment]
These changes have been included in version 1.0.7.
