### ISSUE TITLE
server crash: exception ticking world after setting enabledrowned=false

### ISSUE THREAD

**Issue by DragonNation5523** [SirSquidly/Oceanic-Expanse#30]
[crash-2023-06-01_21.32.44-server.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/11631336/crash-2023-06-01_21.32.44-server.txt)
I had to disable drowned spawning in our server because it was having a compatibility issue with special AI, I followed the instructions to prevent drowned from breaking doors but it didn't work.
Now that i've disabled drowned, we've been having server crashes that suggest corrupted chunks, and I think it's being caused by the server trying to spawn drowned in shipwrecks. I've attached the crash report. It mentions the mods oceanic expanse and Aqua Acrobatics.

**Comment by SirSquidly** [comment]
That's very weird that setting the breaking doors thing didn't work, consider [I and another user got it to work in a previous issue](https://github.com/SirSquidly/Oceanic-Expanse/issues/19). If the Wiki wasn't clear enough, I can update the wording.

Although, the apparent shipwreck crash is an issue, I will be testing that one out.

**Comment by SirSquidly** [comment]
Fixed in development workspace, but just making Shipwrecks _not_ try to spawn Drowned if Drowned are disabled.

**Comment by TheGeneralJR1** [comment]
I think I may have been having this issue to. I hadn't noticed it until I started generating new ocean terrain well after setting drowned to false.

**Comment by SirSquidly** [comment]
Fixed in version 1.0.7.
