### ISSUE TITLE
Issue with Drowned spawning in the Twilight Forest

### ISSUE THREAD

**Issue by TheGeneralJR1** [SirSquidly/Oceanic-Expanse#32]
Where there are water pools at least 3 blocks deep in the Twilight Forest Drowned will spawn en masse. Possibly happens in other dimensions where water pools form. I know RandomTweaks causes Drowned spawn rates to increase, but I don't use it. I do use RandomPatches, but removing it yielded no difference

**Comment by SirSquidly** [comment]
Added a lazy fix by just checking the dimension. I'll expand on this later, as I plan on overhauling most of the mods spawning.

**Comment by SirSquidly** [comment]
Temporarily fixed in version 1.0.7.
