### ISSUE TITLE
OE kelp + Fluidlogged API lighting issue 

### ISSUE THREAD

**Issue by PhoenixStarz** [SirSquidly/Oceanic-Expanse#36]
With Fluidlogged API kelp will grow up to the surface of the water then transmit the light level from the top of the kelp to the base of the kelp, this creates bright patches of light in the sea floor.

Example
![Minecraft 1 12 2 7_13_2023 4_42_23 AM](https://github.com/SirSquidly/Oceanic-Expanse/assets/125336647/5d147fa7-639a-4ca4-8903-1f4b0731313c)

**Comment by SirSquidly** [comment]
Fixed in 1.1.0 I'm pretty sure.

Please re-open the issue if I forgot any specific plants.
