### ISSUE TITLE
Unbrewable Potion of descent

### ISSUE THREAD

**Issue by ElLiox** [SirSquidly/Oceanic-Expanse#37]
OceanicExpanse 1.0.6
it is not possible to brew the potion of descent following the steps on the wiki
the recipe does not appear in JEI either

**Comment by SirSquidly** [comment]
It seems I have _entirely forgotten_ to add the recipe, huh. I'll put that in the upcoming bugfix update.

**Comment by SirSquidly** [comment]
Fixed in development workspace

**Comment by SirSquidly** [comment]
Fixed in version 1.0.7.
