### ISSUE TITLE
[Suggestion] Enchantment Descriptions compatibility

### ISSUE THREAD

**Issue by ElLiox** [SirSquidly/Oceanic-Expanse#38]
It would be nice if the trident enchantments have their description with the Enchantment Descriptions mod

**Comment by SirSquidly** [comment]
This actually has been set up in the development workspace for a bit, along with Potion and JEI descriptions. I just need to put a few more fixes in and push the update. I'll update here when that happens.

**Comment by SirSquidly** [comment]
Added to and released in version 1.0.7.
