### ISSUE TITLE
clams suffocation

### ISSUE THREAD

**Issue by Biviho** [SirSquidly/Oceanic-Expanse#47]
looks like clams are actually entity with 2 blocks hight, this cause them to get suffocated when under a block placed one block higher

**Comment by SirSquidly** [comment]
They... aren't two blocks in height? They are half a block in height, and don't suffocate beneath blocks. They also don't suffocate on land.

In this screenshot, I have enabled hitboxes using `F3 + B`, and you can see that they are more than fine under a block.
![2024-01-10_13 25 55](https://github.com/SirSquidly/Oceanic-Expanse/assets/13826553/e318856b-24a4-4e79-a1d7-3487641ce863)

**Comment by SirSquidly** [comment]
No elaboration has been provided, I'll assume there is not issue then.
