### ISSUE TITLE
[bug] cod does not despawn properly

### ISSUE THREAD

**Issue by darkheadmaster132** [SirSquidly/Oceanic-Expanse#49]
other entites are fine but the cod fish does not despawn after spawning, at 11 chunk render distance i had at least 2000 cod spawned in ocean biome

**Comment by SirSquidly** [comment]
Cod don't have anything special to their spawning or anything that could mark them persistent, so I think this might actually be an issue of too many spawning outright,

Can you confirm that you are using the most recent version of the mod?

**Comment by darkheadmaster132** [comment]
i am using the 1.0.7 version, also i know what the exact problem is now, all of the fish do not despawn (exactly cod, salmon, tropical fish and pufferfish)

i done nothing but test the mod all day at first i though it was something to do with render distance or simulation distance but no so i turned to the most crude way to test

I spawned vanilla squid and some of the modded entites and teleported like 2000 block away (not outside of the render distance) all of the squid despawned but the fish stayed

**Comment by SirSquidly** [comment]
Checking this myself, I found that you are completely correct. They inherit from the Animal class (such as Cows, Pigs, ect) which disallows normal despawning for the sake of player farming.

I already included checks to keep them from overpopulating Oceans, but re-enabling despawning will also be good.

**Comment by SirSquidly** [comment]
Fixed in development workspace. It'll come bundled with a nice content update aswell.

**Comment by SirSquidly** [comment]
Fixed in 1.1.0
