### ISSUE TITLE
some small bugs i found

### ISSUE THREAD

**Issue by darkheadmaster132** [SirSquidly/Oceanic-Expanse#5]
Fish (cod, salmon and tropical fish) entites are always going to the highest water block availble and by doing this glitch between flapping and swimming they're movments are also very jerky especially the baby versions of fish

subtitles for placing/destroying seagrass block are: subtitle.wet_grass_place 

baby drowned does not have 2nd layer on head

**Comment by SirSquidly** [comment]
So, on the first issue, I understand that Fish have the odd flopping animation while on the water surface, but are you also saying that they frequently swim as high up as possible?

In the future, it would be more helpful to report issues individually to keep things as clear as possible.

**Comment by SirSquidly** [comment]
Fixed all the issues here (fish flopping, subtitles, baby drowned rendering) in version 1.0.4.
