### ISSUE TITLE
crash while moving around in the ocean

### ISSUE THREAD

**Issue by Biviho** [SirSquidly/Oceanic-Expanse#63]
hi, i've got a crash caused by the ai trying to cast the path from swim to land.

i think it's caused by some interaction with another mod, but i can't figure it out for now, drowned are already blacklisted from EpicSiegeMod, rought mobs and zombie awareness.

[the log](https://mclo.gs/nV9iyRf)

**Comment by SirSquidly** [comment]
It annoys me how often other mods alter the Drowned.

I'll see if I can force a fix for this.

**Comment by SirSquidly** [comment]
FINALLY fixed in 1.1.1. 

This has been a reoccurring issue, so hopefully, it is finally done.
