### ISSUE TITLE
Disabling the conduit charm results in an errored item

### ISSUE THREAD

**Issue by IcarussOne** [SirSquidly/Oceanic-Expanse#65]
Interacting with it will cause the game to crash.
![error](https://github.com/SirSquidly/Oceanic-Expanse/assets/135455255/a1de7bac-960c-4459-b048-f1566f912cd1)

**Comment by SirSquidly** [comment]
Ah, yikes, I forgot to remove it from the Creative tab! I'll see about fixing that!

**Comment by SirSquidly** [comment]
Fixed in 1.1.1
