### ISSUE TITLE
[Incompatability] Camera won't adjust when swimming

### ISSUE THREAD

**Issue by VoidWarOfficial** [SirSquidly/Oceanic-Expanse#68]
I know it's a mod incompatibility, but I can't seem to think of / figure out which. Included a mod list in-case one of them is obviously an issue
https://pastebin.com/EtHynRbv

**Comment by SirSquidly** [comment]
I am very confused as to what you mean by "Camera won't adjust"

I don't do a single thing with the player's Camera in this mod, so this is very likely not an issue with Oceanic Expanse, but something else.

I'll leave this open for a bit, if there isn't any evidence provided that Oceanic Expanse is responsible for such an issue, then I'll have to close this issue.

**Comment by VoidWarOfficial** [comment]
I am so sorry, I completely forgot it was Aqua Acrobatics that changes swimming, not OE, again, my apologies.
