### ISSUE TITLE
Killing tropical slimes while tropical fish are disabled will spawn invisible fish

### ISSUE THREAD

**Issue by IcarussOne** [SirSquidly/Oceanic-Expanse#69]
While tropical fish are disabled, tropical slimes will still attempt to spawn them but they will be invisible with no visible hitbox. I think it would be best to have this also disabled while tropical fish are disabled or have a separate config option for tropical fish spawning on death.

**Comment by SirSquidly** [comment]
Definitely an oversight, the config has always been a consistent issue.

**Comment by SirSquidly** [comment]
Fixes in 1.1.1
