### ISSUE TITLE
Incompatable with Trident

### ISSUE THREAD

**Issue by SaltOvOFish** [SirSquidly/Oceanic-Expanse#77]
After updating to version 1.1.0 (and the same for 1.1.1), it is not compatible with the Trident MOD. Installing them together will result in an error and the game cannot be launched. Previous versions of the MOD had no compatibility issues with the Trident MOD. The Trident MOD can modify the trident animation added by Oceanic Expanse to its own trident animation.

**Comment by SirSquidly** [comment]
This is caused by the Mixins employed by the Trident Mod, I cannot do much about it on my end.

Along with this, version 1.1.0 of Oceanic Expanse has added animations for most of the Trident.

**Comment by SaltOvOFish** [comment]
> 这是由 Trident Mod 使用的 Mixins 引起的，我对此无能为力。
> 
> 除此之外，Oceanic Expanse 的 1.1.0 版本还为大多数三叉戟添加了动画。

Well, it’s not a big deal. Now that OE has its own trident animation, there’s less need for additional MODs to add similar features.
Additionally, the feel of launching the trident in OE is a bit strange now. It can be launched when it’s close to full charge, and if it’s launched after full charge, the time seems a bit too long. I hope it can be standardized to only launch after full charge, and the charge time could be slightly shortened.

**Comment by SirSquidly** [comment]
> ...It can be launched when it’s close to full charge, and if it’s launched after full charge, the time seems a bit too long. I hope it can be standardized to only launch after full charge, and the charge time could be slightly shortened.

This is completely accurate to Vanilla Trident behavior. The 1st person animation is slightly longer than the actual time to charge.

In OE's 3D person animation, the Trident is charged/ready to throw the second it reaches the same spot the Vanilla Animation has it at.

**Comment by SaltOvOFish** [comment]
Maybe it’s my illusion, thank you for your reply.😂
