### ISSUE TITLE
Incompatibility with ZAWA mod

### ISSUE THREAD

**Issue by XvaleX10** [SirSquidly/Oceanic-Expanse#78]
For some reason the ZAWA mod breaks the generation of Oceanic Expanse mobs

**Comment by SirSquidly** [comment]
Looking into it, this seems to be an issue on ZAWA's end. Issue [188](https://github.com/gkazan/ZAWA/issues/188) on ZAWA has multiple people referring to ZAWA specifically breaking the spawning of Oceanic Mods.

This looks like something is broken on their end.
