### ISSUE TITLE
Ongoing Conflict with Capsule (Crash Fixed)

### ISSUE THREAD

**Issue by Handeril** [SirSquidly/Oceanic-Expanse#8]
Currently, capsules from Capsule are refusing to activate, they just kinda "tick" the item in my hand when I right-click, like I punched with it.

It's better than crashing, which is good.

Apologies if I'm being annoying about this. I currently use Capsule as a means of setting up my modpack's optional "Skyblock Mode".

**Comment by SirSquidly** [comment]
I have loaded Oceanic Expanse 1.0.4 with Capsule 3.4.76 and I have zero issues deploying and capturing using Capsules. 

Can you ensure this is an issue being caused only by these two mods? Is there another mod causing this?

![2023-04-22_14 21 26](https://user-images.githubusercontent.com/13826553/233807149-2e12756d-877d-4450-9288-8ee6ac809b58.png)

**Comment by Handeril** [comment]
So, upon doing further-testing, it seems the newest update of Roguelike Dungeons (The FNAR Fork) or one of the other mods I updated has a high tendency to kill Skyblock worlds while they're generating (or something of that matter) - which causes the appearance of the bug being revived.

Apologies for the inconvenience.

**Comment by SirSquidly** [comment]
It's no inconvenience at all, thank you for identifying the issue.
