### ISSUE TITLE
[Suggestion] Could you add content inspired by this mod?

### ISSUE THREAD

**Issue by XvaleX10** [SirSquidly/Oceanic-Expanse#80]
https://www.curseforge.com/minecraft/mc-mods/fantastic-fish-alpha-v1-4
https://github.com/LittleBreadLoaf/Fantastic-Fish

**Comment by SirSquidly** [comment]
I am always looking for inspiration, including from other mods, so some bits may appear overtime if I have good plans for it.

Although, I will not be doing direct ports or anything, that's work for a separate project.

I am closing this for now, in the future I would prefer Suggestions to be placed in the Discussions.
