### ISSUE TITLE
Submission of Simplified Chinese Language File

### ISSUE THREAD

**Issue by SaltOvOFish** [SirSquidly/Oceanic-Expanse#81]
Hello, I’ve noticed that version 1.1.2 of the MOD has added several new language files, including “Shakespearean English,” “Pirate Speak,” and “LOLCAT.” Are you interested in adding support for more languages? I would like to submit a Chinese language file to you (Includes all content from version 1.1.2).
This language file has already been submitted to “I18nUpdateMod” (a well-known MOD that provides Chinese translations for other MODs) ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/i18nupdatemod)、[Modrinth](https://modrinth.com/mod/i18nupdatemod)、[GitHub](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package)) and has passed their review process and been successfully merged into the project, so there’s no need to worry about the accuracy of the translation. Of course, if you have any suggestions for modifications, please feel free to bring them up, and I will make changes according to your feedback. 
Of course, if you’re not interested in adding more languages at this time, then please disregard my message. Sorry for the disturbance.
[zh_cn.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/15397785/zh_cn.txt)

**Comment by SirSquidly** [comment]
Wait, I let that slip into the 1.1.2 version‽ Yikes, those translations weren't fully completed!

Also I would love to directly add more translations to the mod! I already planned on having feelers out for any translators, so this is a pleasant surprise!

Scanning the I18nUpdateMod GitHub, I see you were the one to upload said translations, and I am incredibly thankful for that! I definitely would like to incorporate the translations, and would like to give any assistance possible to help you!

**Comment by SaltOvOFish** [comment]
I am very pleased that you can say this. The above text already includes translations of all the content in en_us.lang, but there are indeed some minor issues that require your assistance.
Firstly, the annotation text for ‘Conduit Charm,’ ‘Conduit Power when outside of a Conduit’s Range,’ is not included in en_us.lang, so this sentence has not been translated yet. If it can be added later, the corresponding Chinese translation can also be included.
Additionally, there is an issue with the ‘Bucket of Mob.’ The standard Chinese translation in Vanilla is ‘生物(Mob)桶 (Bucket)’, which reverses the order compared to English. For example, ‘Bucket of Cod’ is translated as ‘鳕鱼(Cod)桶(Bucket)’.
However, because the original text given by Oceanic Expanse is 'item.oe.spawn_bucket.name=Bucket of ', this part of the translation cannot differ from the standard Chinese translation in Vanilla for the time being. Could you add a placeholder and change it to ‘Bucket of %s’ (I’m not sure if this change is correct), so that this part can be modified to ‘%s Bucket’ to be consistent with the standard Chinese translation in Vanilla.
I am very happy that you are willing to incorporate the Chinese translation into the MOD. If there are new contents added to the MOD in the future, I will also keep updating this part of the translation. Thank you very much for your help.

**Comment by SirSquidly** [comment]
Both changes (Conduit Charm description moved to Translations, and Bucket name using a format specifier) have been made to the GitHub.

I will push an update for the mod most likely tomorrow, as I am pressed on time today.

Please let me know any other changes or tweaks that would be helpful, I will be happy to implement them.

**Comment by SaltOvOFish** [comment]
![image](https://github.com/SirSquidly/Oceanic-Expanse/assets/125075133/1379e6d6-7118-41ac-b03a-373c0c94fc4f)
Can the comment text in the ‘MOD Config’ section be included in the en_us.lang file? If we add this portion of text, then all the content that appears in the mod should be translatable. This would also assist other translators.
Then there are no other issues. After the new version of the mod is released, I will promptly update the Chinese translation text and submit it to you.

**Comment by SirSquidly** [comment]
In testing, I have found that the in-game Config Comment Text can be overridden by adding new lines to the .lang file, where they use the the config option's name with `.tooltip` added to the end. For example, adding `oe.config.worldGen.enableCoquinaOutcrops.tooltip` to the .lang will allow overriding the in-game comment text for that option.

So, as far as I can tell, the in-game config comment text can already be altered.

Note that this only will alter the in-game displayed text, the Forge's config text file does not support Lang Keys.

**Comment by SaltOvOFish** [comment]
Yes, this is indeed possible. I have spent some time and have completed all the translations for this part, with each line of comments placed under the corresponding option.
Additionally, I have optimized the translations in some areas. Then, based on ‘description.oe.charm.name=Gives Conduit Power when outside of a Conduit’s Range.’ and ‘item.oe.spawn_bucket.name=Bucket of %s’, I translated the corresponding content, hoping they are effective.
This is the TXT file after the modifications. Overall, there should be no issues now. Thank you very much for your help.
[zh_cn.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/15475850/zh_cn.txt)

**Comment by SirSquidly** [comment]
Sorry for taking so long, June and July have been extremely busy for me.

In the newest Commit https://github.com/SirSquidly/Oceanic-Expanse/commit/8bd0b1499e1f7756247623334f16aee6a9d017a7, I have changed Tropical Fish with special names (Such as the Clownfish) to refer to a Translation Key, as they previously were written as an English String in the Config. 

Do you think you can update the Translation File to include the new names? The linked Commit should show how the .lang is laid out. Also, thank you very much for all the help so far, I will be including the Chinese Translation in the upcoming minor update, and I'll add you to the Credits page!

**Comment by SaltOvOFish** [comment]
[zh_cn.txt](https://github.com/user-attachments/files/16319004/zh_cn.txt)


You’re welcome, it was just a piece of cake. Here is the revised TXT file.
Additionally, I have revised two translations that had slight discrepancies with the English version. Now, they are more accurate to the original meaning:
Heavy Boots：配重靴→沉重靴
Mob Stomp：踏击→生物重踏

**Comment by SirSquidly** [comment]
Very nice. I have included the Translations into the newest version of the mod, 1.1.3, and placed a thanks to you in the mod's page.

I would like to stay in touch for any future translation work on the mod, should I just keep this thread open, or move this to the discussions tab?

**Comment by SaltOvOFish** [comment]
> Very nice. I have included the Translations into the newest version of the mod, 1.1.3, and placed a thanks to you in the mod's page.
> 
> I would like to stay in touch for any future translation work on the mod, should I just keep this thread open, or move this to the discussions tab?

I think we should move it to the discussions tab; it seems more convenient there.If needed later, I will also update the subsequent Chinese translation texts there.
