### ISSUE TITLE
Support for RTG.

### ISSUE THREAD

**Issue by MagmaSlime123** [SirSquidly/Oceanic-Expanse#82]
Title.

https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation-unofficial

**Comment by ANightDazingZoroark** [comment]
based on what ive seen in RTG's code the compatibility should be added to RTG itself, which from the looks of things seems fairly straightforward

**Comment by MagmaSlime123** [comment]
RTG is dead. I asked here because of that.

**Comment by SirSquidly** [comment]
Doing such would require making a Fork of RTG to add the compatibility, which is something I am not interested in doing or maintaining. That's a project for someone else to do.

**Comment by SirSquidly** [comment]
Closing this, as there is no followup or development on this planned as of now
