### ISSUE TITLE
I hope to merge the features of Subaquatic

### ISSUE THREAD

**Issue by VillagerGold** [SirSquidly/Oceanic-Expanse#83]
Ocean Expansion is the module that I believe can best achieve 1.13+ocean updates, but there is still a lot of room for improvement compared to similar types of Subaquatics. I hope to learn most of its features

**Comment by SirSquidly** [comment]
Subaquatic does have it's own great qualities, and is a very nice mod in itself.

Also, this isn't a bug, so I'm closing this.
