### ISSUE TITLE
Worldgen bug?

### ISSUE THREAD

**Issue by darkheadmaster132** [SirSquidly/Oceanic-Expanse#84]
I wanted to report a minor bug I encountered in your mod with coral reefs generating in ravines when they spawn next to them. It looks like the coral is generating in the stone within the ravine. I thought you might want to know about this

I've found it challenging to reproduce so it's probably very rare world gen bug, but I thought it was worth mentioning. Thanks for your hard work on the mod, it's been a lot of fun to play with!

![2024-06-13_12 10 16](https://github.com/SirSquidly/Oceanic-Expanse/assets/102760497/22e6617b-c9b6-4dd1-926a-ca9862394de5)

**Comment by SirSquidly** [comment]
Odd quirk, but I wouldn't consider it a bug. It _does_ technically spawn in water.

I don't think I'll be fixing this one, as I like the worldgen being a little odd rarely, makes it very fun to discover.
