### ISSUE TITLE
bonemeal saplings under ceilings deletes sapling

### ISSUE THREAD

**Issue by Sethgno** [SirSquidly/Oceanic-Expanse#9]
bonemealing palm saplings under non-permissible ceilings (i.e. not logs/leaves/dirt) will delete the sapling instead of just preventing its generation if the selected tree gen collides with it.
also, oe:coconut counts as a non-permissible ceiling. unsure if this is preferred but noting it anyway.

**Comment by SirSquidly** [comment]
I'll allow Coconuts to be non-permissible, as I don't want coconuts being deleted by a generating tree.

Fixed in development workspace.

**Comment by zfms4188** [comment]
> I'll allow Coconuts to be non-permissible, as I don't want coconuts being deleted by a generating tree.
> 
> Fixed in development workspace.

When the coconut tree is finished growing, the trunk around it will destroy the block, which should not happen

**Comment by SirSquidly** [comment]
Fixed in version 1.0.5

> When the coconut tree is finished growing, the trunk around it will destroy the block, which should not happen

Please open a separate issue in the future instead of replying to an unrelated one. This issue was also found and fixed in 1.0.5.
