### ISSUE TITLE
[Suggestion] disable items if related mob is disabled

### ISSUE THREAD

**Issue by nocturni** [SirSquidly/Oceanic-Expanse#92]
hiya! i'm making a modpack where every item is unique (consistency is a priority) and i think it'd be cool if when disabling crabs, crab food got disabled too

they currently conflict with mo creatures and i have no way to hide the duplicate items

could that be a thing? thanks a bunch

**Comment by SirSquidly** [comment]
Fixed in 1.1.5

Meat Items now disable when their related mob is disabled
