### ISSUE TITLE
The file extension of the Chinese language file is incorrect

### ISSUE THREAD

**Issue by SaltOvOFish** [SirSquidly/Oceanic-Expanse#93]
![image](https://github.com/user-attachments/assets/01d6ea02-a5dc-4047-ad74-b39a3ca5eb66)
Because I have been using the I18n Chinese translation MOD, I didn’t notice this issue with the new version for the past few days. It wasn’t until I just tried to use the new Chinese language file that came with the mod to replace the old I18n Chinese translation file that I discovered the Simplified Chinese language file had the extension ‘.txt’ instead of the correct ‘.lang’

This should count as a small bug, right? I hope I didn’t use the wrong way to report it

**Comment by SaltOvOFish** [comment]
![image](https://github.com/user-attachments/assets/146fdeb2-a19c-4fe2-9e87-547db8555e1a)
It seems that GitHub does not allow uploading files with the ‘.lang’ format, so in our previous communications, I have been giving you files in the ‘.txt’ format. You need to change the file name from ‘zh_cn.txt’ to ‘zh_cn.lang’. However, I forgot to remind you of this in our previous communications, which was an oversight on my part😂

**Comment by SirSquidly** [comment]
Apologies for that, next bug fix will have that fixed

**Comment by SaltOvOFish** [comment]
OK,Thank you for your hard work👍

**Comment by SirSquidly** [comment]
Fixed in 1.1.4

**Comment by SirSquidly** [comment]
Also, apologies this was left broken for so long, I've been very busy between life and other projects
