### ISSUE TITLE
Crabs and Lobsters should be arthropods

### ISSUE THREAD

**Issue by Kuwagumo** [SirSquidly/Oceanic-Expanse#99]
I didn't see it in the wiki, so guess i should post here. Is it possible to make crabs and lobsters be arthropods, for the sake of bane of arthropods (and possibly other modded features)?

**Comment by SirSquidly** [comment]
Crabs and Lobsters already are Arthropods, I just didn't note it on the Wiki yet,

**Comment by SirSquidly** [comment]
Updated the respective wiki pages to make this clear.
